### ISSUE TITLE
Is this project really in Zanata?

### ISSUE THREAD

**Issue by Jibec** [libguestfs/virt-v2v#1]
hello, as I was checking for libguestfs projects related to Zanata for our migration to Weblate [1], I discovered this project.

The zanata.xml file says translations are handled in virt-v2v, but I can't find any track of this project in Zanata, does it really exists?

[1] https://fedoraproject.org/wiki/L10N_Move_to_Weblate

**Comment by rwmjones** [comment]
It was split from libguestfs a few months ago and maybe we screwed up the transition, but yes the translations are meant to be in Zanata.  Please mail libguestfs@redhat.com for further queries.

**Comment by Jibec** [comment]
If it is using Zanata (which I doubt), then we'll have to migrate it to 
Weblate (or host it directly there).
Should I open a dedicated ticket for this or should we use this one?

**Comment by rwmjones** [comment]
It seems as if I did not create the project on Zanata, although I intended to.  Please email libguestfs@redhat.com for further queries, I will not respond to further requests on this proprietary system.

**Comment by Jibec** [comment]
I'm confused, where is the public big tracker? Bugzilla?
