### ISSUE TITLE
windows 2012R2 not finding disks

### ISSUE THREAD

**Issue by madmax01** [libguestfs/virt-v2v#13]
i used the virt-v2v on

Alma 8.6
1.42 virt-v2v
libvirt 8.0
qemu 6.2

when i try to convert i get following info about GPO:

virt-v2v: warning: this guest has Windows Group Policy Objects (GPO) and a
new virtio block device driver was installed.  In some circumstances, Group
Policy may prevent new drivers from working (resulting in a 7B boot error).
 If this happens, try disabling Group Policy before doing the conversion.
-------

Windows vm have only local group policy and i disabled computer and user policy temp. When trying to boot the vm no disks found.

command i used:
virt-v2v -i ova test.ova -of qcow2  -on test.qcow2 -os convert

i can only boot when i change vd to hd and to disable the driver signature enforcement

do i miss something?

**Comment by rwmjones** [comment]
There's not enough information to tell what's going on, but the warning about GPO is real - you do need to disable the policy before conversion.

**Comment by madmax01** [comment]
may not very helpful if a ticket just getting closed without telling what's required for Analyze.

just as Feedback.

[Ok so i figured out what's the Issue.](virt-v2v: This guest has virtio drivers installed.)    = this info is not 100% valid. Seems there is missing an full validation if driver is really installed. Defo no driver installed. also with GPO disabled. Missleading Info.

why i'am saying it is > i tested to install latest virtio-win drivers to 2012R2. and the installer fails completely

Manual install before convert:

225-2 = fails
225-1 = fails
217-2 = fails
217-1 = fails
215-2 = works
-----------------------------------------

assuming virt-v2v tries to invoke > but not catching the error about failed installs.

may helpfully to expose more infos for Evidence for Installation.
------------
But is not a hard issue > worst case its always possible to install everything before on old hypervisor - export and then convert without invoke coverage

thx
