### ISSUE TITLE
Running Make result in error: This expression has type int64 but an expression was expected of type int32

### ISSUE THREAD

**Issue by LSD4me** [libguestfs/virt-v2v#28]
OS
Linux hostname 5.15.0-101.103.2.1.el8uek.x86_64 #2 SMP Mon May 1 20:11:30 PDT 2023 x86_64 x86_64 x86_64 GNU/Linux

OCaml
The OCaml toplevel, version 4.07.0

virt-v2v 
GA and Latest Tags result in same error

Making all in lib
make[2]: Entering directory '/opt/virt-v2v/lib'
  CC       libmlv2vlib_a-dummy.o
  OCAMLCMI config.cmi
  OCAMLOPT config.cmx
  OCAMLCMI types.cmi
  OCAMLOPT types.cmx
  OCAMLCMI utils.cmi
  OCAMLOPT utils.cmx
File "utils.ml", line 253, characters 34-37:
Error: This expression has type int64 but an expression was expected of type
         int32
make[2]: *** [Makefile:927: utils.cmx] Error 2
make[2]: Leaving directory '/opt/virt-v2v/lib'
make[1]: *** [Makefile:846: all-recursive] Error 1
make[1]: Leaving directory '/opt/virt-v2v'
make: *** [Makefile:764: all] Error 2

I tried looking at the lib/utils.ml file on 250 but i dont know OCaml language ;(

Any idea whats up here?

**Comment by LSD4me** [comment]
Version of LIBNBD was 1.6 (Old) Newer version resolved this issue

**Comment by rwmjones** [comment]
Yes this was unfortunately the one time ever we changed an API in libnbd.  Shouldn't happen in future.
