### ISSUE TITLE
Support for PhotonOS

### ISSUE THREAD

**Issue by prakashmishra1598** [libguestfs/virt-v2v#33]
Hi Folks,

I ran into the following failure while trying to migrate a PhotonOS(https://vmware.github.io/photon/) guest with virt-v2v where virt-v2v complained of not being able to detect the distro of the guest. Logs: 
```
Failed to determine unit we run in, ignoring: No data available
guestfsd: => inspect_get_distro (0x1e4) took 0.01 secs
libguestfs: trace: v2v: inspect_get_distro = "unknown"
i_root = /dev/sda3
i_type = linux
i_distro = unknown
i_osinfo = unknown
i_arch = x86_64
i_major_version = 5
i_minor_version = 0
i_package_format = unknown
i_package_management = unknown
i_product_name = VMware Photon OS 5.0
i_product_variant = unknown
i_windows_systemroot = 
i_windows_software_hive = 
i_windows_system_hive = 
i_windows_current_control_set = 

virt-v2v: error: inspection could not detect the source guest (or physical machine).

Assuming that you are running virt-v2v/virt-p2v on a source which is supported (and not, for example, a blank dis
k), then this should not happen.

Inspection field ‘i_distro’ was ‘unknown’.
rm -rf -- '/tmp/v2vnbdkit.bcTLgc'
rm -rf -- '/tmp/v2v.tCVBMC'
libguestfs: trace: v2v: close
```

Full logs gist: https://gist.github.com/prakashmishra1598/60e6f814b9fc5014ff3dae020e77303b

Based on discussions here: https://github.com/kubev2v/forklift/issues/494#issuecomment-1666780271, the support is needed at virt-v2v level and I wanted to continue the discussion here to understand the efforts required to add support for PhotonOS in virt-v2v

**Comment by rwmjones** [comment]
While we periodically get requests for supporting Photon, it isn't supported by virt-v2v and support for it isn't likely to happen any time soon.  Last time I looked at this topic, the problem was the OS is some kind of immutable OS (like CoreOS etc), and so could never be modified by virt-v2v.
