### ISSUE TITLE
virt-v2v didn't find vmdk file

### ISSUE THREAD

**Issue by gbeck75** [libguestfs/virt-v2v#5]
Converting a VMware guest from vmx+vmdk file failed claiming there is no disk:

$ virt-v2v -i vmx KR\ C\,\ V8.3.OL_Build07.vmx -o qemu -os qemu -v -x      
virt-v2v: virt-v2v 1.43.4 (x86_64)
libvirt version: 7.0.0
[   0.0] Opening the source -i vmx KR C, V8.3.OL_Build07.vmx
VMX file:
.encoding = "windows-1252"
config.version = "8"
virtualHW.version = "7"
scsi0.present = "TRUE"
scsi0.virtualDev = "lsisas1068"
memsize = "2048"
mem.hotadd = "TRUE"
ide0:0.present = "TRUE"
ide0:0.fileName = "KR C, V8.3.OL_Build07.vmdk"
ethernet0.present = "TRUE"
ethernet0.connectionType = "bridged"
ethernet0.virtualDev = "e1000"
ethernet0.wakeOnPcktRcv = "FALSE"
ethernet0.addressType = "generated"
usb.present = "TRUE"
ehci.present = "TRUE"
sound.present = "TRUE"
sound.startConnected = "FALSE"
sound.fileName = "-1"
sound.autodetect = "TRUE"
mks.enable3d = "FALSE"
serial0.present = "TRUE"
serial0.fileType = "thinprint"
pciBridge0.present = "TRUE"
pciBridge4.present = "TRUE"
pciBridge4.virtualDev = "pcieRootPort"
pciBridge4.functions = "8"
pciBridge5.present = "TRUE"
pciBridge5.virtualDev = "pcieRootPort"
pciBridge5.functions = "8"
pciBridge6.present = "TRUE"
pciBridge6.virtualDev = "pcieRootPort"
pciBridge6.functions = "8"
pciBridge7.present = "TRUE"
pciBridge7.virtualDev = "pcieRootPort"
pciBridge7.functions = "8"
vmci0.present = "TRUE"
roamingVM.exitBehavior = "go"
displayName = "KR C, V8.3.OL_Build07"
guestOS = "windows7"
nvram = "KR C, V8.3.OL_Build06.nvram"
virtualHW.productCompatibility = "hosted"
printers.enabled = "TRUE"
easyInstall.keepFloppy = "TRUE"
extendedConfigFile = "KR C, V8.3.OL_Build07.vmxf"
numvcpus = "2"
cpuid.coresPerSocket = "2"
ethernet0.generatedAddress = "00:0c:29:b2:85:86"
tools.syncTime = "FALSE"
uuid.location = "56 4d 1f 4a 50 65 9e ae-4c 73 72 86 4c b2 85 86"
uuid.bios = "56 4d 1f 4a 50 65 9e ae-4c 73 72 86 4c b2 85 86"
cleanShutdown = "TRUE"
replay.supported = "FALSE"
unity.wasCapable = "FALSE"
replay.filename = ""
ide0:0.redo = ""
pciBridge0.pciSlotNumber = "17"
pciBridge4.pciSlotNumber = "21"
pciBridge5.pciSlotNumber = "22"
pciBridge6.pciSlotNumber = "23"
pciBridge7.pciSlotNumber = "24"
scsi0.pciSlotNumber = "160"
usb.pciSlotNumber = "32"
ethernet0.pciSlotNumber = "33"
sound.pciSlotNumber = "34"
ehci.pciSlotNumber = "35"
vmci0.pciSlotNumber = "36"
scsi0.sasWWID = "50 05 05 6a 50 65 9e a0"
vmotion.checkpointFBSize = "16777216"
usb:0.present = "TRUE"
usb:1.present = "TRUE"
ethernet0.generatedAddressOffset = "0"
vmci0.id = "761629234"
usb:1.deviceType = "hub"
usb:0.deviceType = "mouse"
ethernet0.linkStatePropagation.enable = "TRUE"
isolation.tools.hgfs.disable = "TRUE"
sharedFolder.maxNum = "1"
hgfs.mapRootShare = "FALSE"
sharedFolder0.present = "FALSE"
ide1:0.present = "FALSE"
floppy0.present = "FALSE"

parsed VMX tree:
namespace '':
    encoding = "windows-1252"
cleanshutdown = "TRUE"
namespace 'config':
    version = "8"
namespace 'cpuid':
    corespersocket = "2"
displayname = "KR C, V8.3.OL_Build07"
namespace 'easyinstall':
    keepfloppy = "TRUE"
namespace 'ehci':
    pcislotnumber = "35"
    present = "TRUE"
namespace 'ethernet0':
    addresstype = "generated"
    connectiontype = "bridged"
    generatedaddress = "00:0c:29:b2:85:86"
    generatedaddressoffset = "0"
    namespace 'linkstatepropagation':
        enable = "TRUE"
    pcislotnumber = "33"
    present = "TRUE"
    virtualdev = "e1000"
    wakeonpcktrcv = "FALSE"
extendedconfigfile = "KR C, V8.3.OL_Build07.vmxf"
namespace 'floppy0':
    present = "FALSE"
guestos = "windows7"
namespace 'hgfs':
    maprootshare = "FALSE"
namespace 'ide0:0':
    filename = "KR C, V8.3.OL_Build07.vmdk"
    present = "TRUE"
    redo = ""
namespace 'ide1:0':
    present = "FALSE"
namespace 'isolation':
    namespace 'tools':
        namespace 'hgfs':
            disable = "TRUE"
namespace 'mem':
    hotadd = "TRUE"
memsize = "2048"
namespace 'mks':
    enable3d = "FALSE"
numvcpus = "2"
nvram = "KR C, V8.3.OL_Build06.nvram"
namespace 'pcibridge0':
    pcislotnumber = "17"
    present = "TRUE"
namespace 'pcibridge4':
    functions = "8"
    pcislotnumber = "21"
    present = "TRUE"
    virtualdev = "pcieRootPort"
namespace 'pcibridge5':
    functions = "8"
    pcislotnumber = "22"
    present = "TRUE"
    virtualdev = "pcieRootPort"
namespace 'pcibridge6':
    functions = "8"
    pcislotnumber = "23"
    present = "TRUE"
    virtualdev = "pcieRootPort"
namespace 'pcibridge7':
    functions = "8"
    pcislotnumber = "24"
    present = "TRUE"
    virtualdev = "pcieRootPort"
namespace 'printers':
    enabled = "TRUE"
namespace 'replay':
    filename = ""
    supported = "FALSE"
namespace 'roamingvm':
    exitbehavior = "go"
namespace 'scsi0':
    pcislotnumber = "160"
    present = "TRUE"
    saswwid = "50 05 05 6a 50 65 9e a0"
    virtualdev = "lsisas1068"
namespace 'serial0':
    filetype = "thinprint"
    present = "TRUE"
namespace 'sharedfolder':
    maxnum = "1"
namespace 'sharedfolder0':
    present = "FALSE"
namespace 'sound':
    autodetect = "TRUE"
    filename = "-1"
    pcislotnumber = "34"
    present = "TRUE"
    startconnected = "FALSE"
namespace 'tools':
    synctime = "FALSE"
namespace 'unity':
    wascapable = "FALSE"
namespace 'usb':
    pcislotnumber = "32"
    present = "TRUE"
namespace 'usb:0':
    devicetype = "mouse"
    present = "TRUE"
namespace 'usb:1':
    devicetype = "hub"
    present = "TRUE"
namespace 'uuid':
    bios = "56 4d 1f 4a 50 65 9e ae-4c 73 72 86 4c b2 85 86"
    location = "56 4d 1f 4a 50 65 9e ae-4c 73 72 86 4c b2 85 86"
namespace 'virtualhw':
    productcompatibility = "hosted"
    version = "7"
namespace 'vmci0':
    id = "761629234"
    pcislotnumber = "36"
    present = "TRUE"
namespace 'vmotion':
    checkpointfbsize = "16777216"
    source name: KR C, V8.3.OL_Build07
hypervisor type: vmware
       VM genid: 
         memory: 2147483648 (bytes)
       nr vCPUs: 2
     CPU vendor: 
      CPU model: 
   CPU topology: sockets: 1 cores/socket: 2 threads/core: 1
   CPU features: 
       firmware: bios
        display: 
          video: 
          sound: 
disks:

removable media:

NICs:
        Bridge "ethernet0" mac: 00:0c:29:b2:85:86 [e1000]

virt-v2v: error: source has no hard disks!

**Comment by rwmjones** [comment]
See the mailing list: https://listman.redhat.com/archives/libguestfs/2021-March/msg00116.html

**Comment by gbeck75** [comment]
Thanks, that get me started
