### ISSUE TITLE
Hello is there a way to disable installing virtio drivers when converting

### ISSUE THREAD

**Issue by gongzuokuangwang** [libguestfs/virt-v2v#55]
Hello, I am just starting to use virt-v2v. 

I was trying to convert a windows ova file to `libvirt`. 
In the process, virt-v2v was trying to install some drivers. 
I kind of wish for a "vanilla" conversion, without any kind of modification of the guest. 
Is it possible to disable the virtio? 
I read the man page, however, I did not find any clue. Any ideas?  Thanks in advance

**Comment by gongzuokuangwang** [comment]
Thank you very much for the reply. 

> You can simply not attach the virtio-win ISO or make sure virtio-win is not installed

Is there a command line option for this? I didn't find it in the man page. 

I believe it would be better to have a command line option than modifying the package management system

**Comment by rwmjones** [comment]
There's no specific option but you might try playing with the `VIRTIO_WIN` environment variable to see if you can make it do what you want:

https://github.com/libguestfs/libguestfs-common/blob/830cbdcf4321f289ccfea9ac1e69198678da0a8d/mlcustomize/inject_virtio_win.ml#L77-L84

**Comment by gongzuokuangwang** [comment]
Thank you very much.
