### ISSUE TITLE
Interface name was changed after converted

### ISSUE THREAD

**Issue by nguyenhuukhoi** [libguestfs/virt-v2v#62]
Hello.
I am using virt-v2v to convert vmx to openstack but after that interface name was changed. Would we have solutions for that?
Thank you.

**Comment by rwmjones** [comment]
Virt-v2v doesn't currently preserve network interface names during conversion.  But see:

https://issues.redhat.com/browse/MTV-1491
https://issues.redhat.com/browse/MTV-1497

(and probably more if you search around the "MTV" topic there)

**Comment by nguyenhuukhoi** [comment]
Thank you very much.
Would we support this feature in the future?
Nguyen Huu Khoi
