### ISSUE TITLE
virt-v2v convert vmware vm to openstack ssl error

### ISSUE THREAD

**Issue by sosogengdongni** [libguestfs/virt-v2v#63]
When use virt-v2v convert vmware vm to openstack raise ‘SSL peer certificate or SSH remote key was not OK (60)’ error.

**on openstack execute:**
virt-v2v -ic vpx://192.168.100.134/Datacenter/esxi --insecure -op local -os /home/test test-linux

![图像](https://github.com/user-attachments/assets/019deb10-5c9a-46c8-9904-012c26497de1)

**The following solution was used, but it was not resolved：**

1.sudo cp /path/to/your/certificate.crt /usr/local/share/ca-certificates/
 sudo update-ca-certificates

2.export LIBGUESTFS_BACKEND_SETTINGS=network_no_verify=1

**Comment by rwmjones** [comment]
Change the libvirt URI to `vpx://192.168.100.134/Datacenter/esxi?no_verify=1`

> 2.export LIBGUESTFS_BACKEND_SETTINGS=network_no_verify=1

This does nothing.
