### ISSUE TITLE
RFE: virt-v2v: Support conversion of FreeBSD guests

### ISSUE THREAD

**Issue by tcler** [libguestfs/virt-v2v#7]
get fail while convert EMC OneFS simulator(based on FreeBSD) with virt-v2v:
'''
[jianhong@fstest 9.1.0.0]$ virt-v2v -i ova 9.1.0.0.ova -o local -os tmp
[   0.0] Opening the source -i ova 9.1.0.0.ova
[   1.9] Creating an overlay to protect the source from being modified
[   6.3] Opening the overlay
[  14.6] Inspecting the overlay
virt-v2v: error: mount: mount_stub: /dev/mirror/root0: No such file or
directory

If reporting bugs, run virt-v2v with debugging enabled and include the
complete output:

  virt-v2v -v -x [...]
'''

Application scenario:
 deploy EMC OneFS simulator automatically for automate tests
 see also: https://bugzilla.redhat.com/show_bug.cgi?id=1947291#c2

**Comment by rwmjones** [comment]
On Fri, Jun 04, 2021 at 03:38:13AM -0700, tcler.yin wrote:
> get fail while convert EMC OneFS simulator(based on FreeBSD) with virt-v2v:
> '''
> ***@***.*** 9.1.0.0]$ virt-v2v -i ova 9.1.0.0.ova -o local -os tmp
> [ 0.0] Opening the source -i ova 9.1.0.0.ova
> [ 1.9] Creating an overlay to protect the source from being modified
> [ 6.3] Opening the overlay
> [ 14.6] Inspecting the overlay
> virt-v2v: error: mount: mount_stub: /dev/mirror/root0: No such file or
> directory
> 
> If reporting bugs, run virt-v2v with debugging enabled and include the
> complete output:
> 
> virt-v2v -v -x [...]
> '''
> 
> Application scenario:
> deploy EMC OneFS simulator automatically for automate tests
> see also: https://bugzilla.redhat.com/show_bug.cgi?id=1947291#c2

I don't know what "EMC OneFS simulator" is, but virt-v2v only supports
certain guests:

https://libguestfs.org/virt-v2v-support.1.html

Adding support for new guest types is complicated.

Rich.

-- 
Richard Jones, Virtualization Group, Red Hat http://people.redhat.com/~rjones
Read my programming and virtualization blog: http://rwmj.wordpress.com
Fedora Windows cross-compiler. Compile Windows programs, test, and
build Windows installers. Over 100 libraries supported.
http://fedoraproject.org/wiki/MinGW
